describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.selenium.dev/selenium/web/web-form.html')
    cy.get('#my-text-id').type('some text')
    cy.get(':nth-child(1) > :nth-child(2) > .form-control').type('password')
    cy.get(':nth-child(1) > :nth-child(3) > .form-control').type('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
    cy.get(':nth-child(1) > :nth-child(4) > .form-control').should('be.disabled')
    cy.get(':nth-child(1) > :nth-child(5) > .form-control').should('not.be.disabled')
    cy.get('[name="my-select"]').select('1')
    cy.get('#my-options option').should('have.length', 5)
      .first().should('have.value', 'San Francisco')
      .next().should('have.value', 'New York')
      .next().should('have.value', 'Seattle')
      .next().should('have.value', 'Los Angeles')
      .next().should('have.value', 'Chicago')
    cy.get('[name="my-datalist"]').type('New York')
    cy.uploadFile()
    cy.get('[id="my-check-1"]').should('be.checked')
    cy.get('[id="my-check-2"]').should('not.be.checked')
    cy.contains('Submit').click()
    cy.get('#message').should('have.text', 'Received!')

  })
})